name: Sync to GitLab

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Push code to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_PAT }}@gitlab.com/YourUsername/YourRepository.git
          git push --force gitlab main
